[theme]
primaryColor             = "#004D98"
backgroundColor          = "#FAFAFA"
secondaryBackgroundColor = "#EEF4FB"
textColor                = "#111111"
font                     = "sans serif"

[server]
headless = true
